export const SET_LOADING = "SET_LOADING"
export const TOGGLE_FORM = "TOGGLE_FORM";

// Tutor Action Types
export const FETCH_TUTORS = "FETCH_TUTORS";
export const FETCH_TUTORS_ERROR = "FETCH_TUTORS_ERROR"
export const FETCH_TUTOR_FORM = "FETCH_TUTOR_FORM";
export const FETCH_TUTOR_FORM_ERROR = "FETCH_TUTOR_FORM_ERROR"
export const FETCH_TUTOR_DETAIL = "FETCH_TUTOR_DETAIL";
export const FETCH_TUTOR_DETAIL_ERROR = "FETCH_TUTOR_DETAIL_ERROR";
export const FETCH_TUTOR_EDUCATION_FORMFIELD = "FETCH_TUTOR_EDUCATION_FORMFIELD";
export const FETCH_TUTOR_EDUCATION_FORMFIELD_ERROR = "FETCH_TUTOR_EDUCATION_FORMFIELD_ERROR"
export const ADD_TEACHER_EDUCATION_DETAILS = "ADD_TEACHER_EDUCATION_DETAILS";
export const ADD_TEACHER_EDUCATION_DETAILS_ERROR = "ADD_TEACHER_EDUCATION_DETAILS_ERROR";
export const UPDATE_TEACHER_EDUCATION_DETAILS = "UPDATE_TEACHER_EDUCATION_DETAILS";
export const UPDATE_TEACHER_EDUCATION_DETAILS_ERROR = "UPDATE_TEACHER_EDUCATION_DETAILS_ERROR";

// Student Action Types
export const FETCH_STUDENTS = "FETCH_STUDENTS";
export const FETCH_STUDENTS_ERROR = "FETCH_STUDENTS_ERROR";
export const FETCH_STUDENTS_DETAILS = "FETCH_STUDENTS_DETAILS";
export const FETCH_STUDENTS_DETAILS_ERROR = "FETCH_STUDENTS_DETAILS_ERROR"
export const FETCH_STUDENT_FORM = "FETCH_STUDENT_FORM";
export const FETCH_STUDENT_FORM_ERROR = "FETCH_STUDENT_FORM_ERROR";
export const ADD_STUDENT = "ADD_STUDENT";
export const ADD_STUDENT_ERROR = "ADD_STUDENT_ERROR";
export const FETCH_PARENT_FORM = "FETCH_PARENT_FORM";
export const FETCH_PARENT_FORM_ERROR = "FETCH_PARENT_FORM_ERROR";
export const FETCH_EDIT_PARENT_FORM = "FETCH_EDIT_PARENT_FORM";
export const FETCH_EDIT_PARENT_FORM_ERROR = "FETCH_EDIT_PARENT_FORM_ERROR";
export const ADD_PARENT_DATA = "ADD_PARENT_DATA"
export const ADD_PARENT_DATA_ERROR = "ADD_PARENT_DATA_ERROR";
export const UPDATE_PARENT_DATA = "UPDATE_PARENT_DATA"
export const UPDATE_PARENT_DATA_ERROR = "UPDATE_PARENT_DATA_ERROR"
export const FETCH_EDUCATION_FORM = "FETCH_EDUCATION_FORM";
export const FETCH_EDUCATION_FORM_ERROR = "FETCH_EDUCATION_FORM_ERROR";
export const ADD_STUDENT_EDUCATION_DATA = "ADD_STUDENT_EDUCATION_DATA";
export const ADD_STUDENT_EDUCATION_DATA_ERROR = "ADD_STUDENT_EDUCATION_DATA_ERROR";
export const FETCH_STUDENT_FEES_DATA = "FETCH_FEES_DATA";
export const FETCH_STUDENT_FEES_DATA_ERROR = "FETCH_FEES_DATA_ERROR";