export const SET_LOADING = "SET_LOADING"
export const TOGGLE_FORM = "TOGGLE_FORM";

// Tutor Action Types
export const FETCH_TUTORS = "FETCH_TUTORS";
export const FETCH_TUTORS_ERROR = "FETCH_TUTORS_ERROR"
export const FETCH_TUTOR_FORM = "FETCH_TUTOR_FORM";
export const FETCH_TUTOR_FORM_ERROR = "FETCH_TUTOR_FORM_ERROR"
export const FETCH_TUTOR_DETAIL = "FETCH_TUTOR_DETAIL";
export const FETCH_TUTOR_DETAIL_ERROR = "FETCH_TUTOR_DETAIL_ERROR";
export const FETCH_TUTOR_EDUCATION_FORMFIELD = "FETCH_TUTOR_EDUCATION_FORMFIELD";
export const FETCH_TUTOR_EDUCATION_FORMFIELD_ERROR = "FETCH_TUTOR_EDUCATION_FORMFIELD_ERROR"
export const ADD_TEACHER_EDUCATION_DETAILS = "ADD_TEACHER_EDUCATION_DETAILS";
export const ADD_TEACHER_EDUCATION_DETAILS_ERROR = "ADD_TEACHER_EDUCATION_DETAILS_ERROR";
export const UPDATE_TEACHER_EDUCATION_DETAILS = "UPDATE_TEACHER_EDUCATION_DETAILS";
export const UPDATE_TEACHER_EDUCATION_DETAILS_ERROR = "UPDATE_TEACHER_EDUCATION_DETAILS_ERROR";

// Student Action Types
export const FETCH_STUDENTS = "FETCH_STUDENTS";
export const FETCH_STUDENTS_ERROR = "FETCH_STUDENTS_ERROR";
export const FETCH_STUDENTS_DETAILS = "FETCH_STUDENTS_DETAILS";
export const FETCH_STUDENTS_DETAILS_ERROR = "FETCH_STUDENTS_DETAILS_ERROR"
export const FETCH_STUDENT_FORM = "FETCH_STUDENT_FORM";
export const FETCH_STUDENT_FORM_ERROR = "FETCH_STUDENT_FORM_ERROR";
export const ADD_STUDENT = "ADD_STUDENT";
export const ADD_STUDENT_ERROR = "ADD_STUDENT_ERROR";
export const FETCH_PARENT_FORM = "FETCH_PARENT_FORM";
export const FETCH_PARENT_FORM_ERROR = "FETCH_PARENT_FORM_ERROR";
export const FETCH_EDIT_PARENT_FORM = "FETCH_EDIT_PARENT_FORM";
export const FETCH_EDIT_PARENT_FORM_ERROR = "FETCH_EDIT_PARENT_FORM_ERROR";
export const ADD_PARENT_DATA = "ADD_PARENT_DATA"
export const ADD_PARENT_DATA_ERROR = "ADD_PARENT_DATA_ERROR";
export const UPDATE_PARENT_DATA = "UPDATE_PARENT_DATA"
export const UPDATE_PARENT_DATA_ERROR = "UPDATE_PARENT_DATA_ERROR"
export const FETCH_EDUCATION_FORM = "FETCH_EDUCATION_FORM";
export const FETCH_EDUCATION_FORM_ERROR = "FETCH_EDUCATION_FORM_ERROR";
export const ADD_STUDENT_EDUCATION_DATA = "ADD_STUDENT_EDUCATION_DATA";
export const ADD_STUDENT_EDUCATION_DATA_ERROR = "ADD_STUDENT_EDUCATION_DATA_ERROR";
export const FETCH_STUDENT_FEES_DATA = "FETCH_FEES_DATA";
export const FETCH_STUDENT_FEES_DATA_ERROR = "FETCH_FEES_DATA_ERROR";
export const UPDATE_STUDENT_EDUCATION_DETAILS = "UPDATE_STUDENT_EDUCATION_DETAILS";
export const UPDATE_STUDENT_EDUCATION_DETAILS_ERROR = "UPDATE_STUDENT_EDUCATION_DETAILS_ERROR"

// Fees Action Types
export const FETCH_FEES_FORM_FIELDS = "FETCH_FEES_FORM_FIELDS";
export const FETCH_FEES_FORM_FIELDS_ERROR = "FETCH_FEES_FORM_FIELDS_ERROR";
export const FETCH_FEES = "FETCH_FEES";
export const FETCH_FEES_ERROR = "FETCH_FEES_ERROR";
export const ADD_FEES = "ADD_FEES";
export const ADD_FEES_ERROR = "ADD_FEES_ERROR";
export const TOGGLE_IMPORT = "TOGGLE_IMPORT";
export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_FILE_ERROR = "UPLOAD_FILE_ERROR";
export const SEACRH_FEES = "SEACRH_FEES";
export const SEACRH_FEES_ERROR = "SEACRH_FEES_ERROR";
export const DOWNLOAD_FEES = "DOWNLOAD_FEES";
export const DOWNLOAD_FEES_ERROR = "DOWNLOAD_FEES_ERROR";

// Exam constant types
export const FETCH_EXAMS = "FETCH_EXAMS";
export const FETCH_EXAMS_ERROR = "FETCH_EXAMS_ERROR";
export const ADD_EXAM = "ADD_EXAM"
export const ADD_EXAM_ERROR = "ADD_EXAM_ERROR";
export const FECTH_EXAM_FORM_FIELDS = "FECTH_EXAM_FORM_FIELDS";
export const FECTH_EXAM_FORM_FIELDS_ERROR = "FECTH_EXAM_FORM_FIELDS_ERROR"
export const DELETE_EXAM = "DELETE_EXAM";
export const DELETE_EXAM_ERROR = "DELETE_EXAM_ERROR"

// Dashboard constant types
export const FETCH_STUDENT_ATTENDENCE = 'FETCH_STUDENT_ATTENDENCE';
export const FETCH_STUDENT_ATTENDENCE_ERROR = 'FETCH_STUDENT_ATTENDENCE_ERROR';
export const FETCH_TUTOR_ATTENDENCE = "FETCH_TUTOR_ATTENDENCE";
export const FETCH_TUTOR_ATTENDENCE_ERROR = "FETCH_TUTOR_ATTENDENCE_ERROR";

export const TOGGLE_STUDENT_ATTENDENCE_ELEMENT = "TOGGLE_STUDENT_ATTENDENCE_ELEMENT";

export const SEARCH_STUDENT_ATTENDENCE_BY_ID = "SEARCH_STUDENT_ATTENDENCE_BY_ID";
export const SEARCH_STUDENT_ATTENDENCE_BY_ID_ERROR = "SEARCH_STUDENT_ATTENDENCE_BY_ID_ERROR";
export const SEARCH_STUDENT_BY_ID = "SEARCH_STUDENT_BY_ID";
export const SEARCH_STUDENT_BY_ID_ERROR = "SEARCH_STUDENT_BY_ID_ERROR";
export const MARK_STUDENT_ATTENDENCE = "MARK_STUDENT_ATTENDENCE";
export const MARK_STUDENT_ATTENDENCE_ERROR = "MARK_STUDENT_ATTENDENCE_ERROR";

export const MARK_STUDENT_ABSENCE = "MARK_STUDENT_ABSENCE";
export const MARK_STUDENT_ABSENCE_ERROR = "MARK_STUDENT_ABSENCE_ERROR";
